# Generated by Django 3.1.7 on 2021-04-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hammer", "0002_auto_20210331_2150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacksmith",
            name="level",
        ),
        migrations.AddField(
            model_name="blacksmith",
            name="gold",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heating_work", models.IntegerField()),
                ("holding_work", models.IntegerField()),
                ("hitting_work", models.IntegerField()),
                ("shaping_work", models.IntegerField()),
                (
                    "blacksmith",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="hammer.blacksmith"
                    ),
                ),
            ],
        ),
    ]
