# Generated by Django 3.1.7 on 2021-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hammer", "0003_auto_20210401_1950"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.IntegerField(choices=[(1, "Waiting"), (2, "In progress")], default=1),
        ),
    ]
