# Generated by Django 3.1.7 on 2021-04-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammer', '0004_auto_20210403_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-status']},
        ),
    ]
